//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.NiryoMoveit
{
    public class Base_frame : Message
    {
        public const string RosMessageName = "niryo_moveit/Base_frame";

        public Geometry.Pose pose;

        public Base_frame()
        {
            this.pose = new Geometry.Pose();
        }

        public Base_frame(Geometry.Pose pose)
        {
            this.pose = pose;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(pose.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.pose.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "Base_frame: " +
            "\npose: " + pose.ToString();
        }
    }
}
