arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - PSM1_outer_yaw
    - PSM1_outer_pitch
    - PSM1_outer_insertion
    - PSM1_outer_roll
    - PSM1_outer_wrist_pitch
    - PSM1_outer_wrist_yaw
  gains: 
    PSM1_outer_yaw: {p: 100.0, i: 0.0, d: 3.0}
    PSM1_outer_pitch: {p: 100.0, i: 0.0, d: 3.0}
    PSM1_outer_insertion: {p: 6000.0, i: 0.0, d: 80.0}
    PSM1_outer_roll: {p: 4.0, i: 0.002, d: 0.03}
    PSM1_outer_wrist_pitch: {p: 4.0, i: 0.002, d: 0.03}
    PSM1_outer_wrist_yaw: {p: 4.0, i: 0.002, d: 0.03}
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    PSM1_outer_yaw: {trajectory: 0.1, goal: 0.1}
    PSM1_outer_pitch: {trajectory: 0.1, goal: 0.1}
    PSM1_outer_insertion: {trajectory: 0.1, goal: 0.1}
    PSM1_outer_roll: {trajectory: 0.1, goal: 0.1}
    PSM1_outer_wrist_pitch: {trajectory: 0.1, goal: 0.1}
    PSM1_outer_wrist_yaw: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 25
  action_monitor_rate: 10
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - PSM1_outer_yaw
    - PSM1_outer_pitch
    - PSM1_outer_insertion
    - PSM1_outer_roll
    - PSM1_outer_wrist_pitch
    - PSM1_outer_wrist_yaw
  gains: 
    PSM1_outer_yaw: {p: 100.0, i: 0.0, d: 3.0}
    PSM1_outer_pitch: {p: 100.0, i: 0.0, d: 3.0}
    PSM1_outer_insertion: {p: 6000.0, i: 0.0, d: 80.0}
    PSM1_outer_roll: {p: 4.0, i: 0.002, d: 0.03}
    PSM1_outer_wrist_pitch: {p: 4.0, i: 0.002, d: 0.03}
    PSM1_outer_wrist_yaw: {p: 4.0, i: 0.002, d: 0.03}