PSM1_Group:
  kinematics_solver: PSM1_PSM1_Group_ikfast_plugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005

PSM2_Group:
  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005

ECM_Group:
  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
